name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release

      # Run Tests
      - name: Test
        run: dotnet test --configuration Release

      # Set a lowercase username for Docker image tagging
      - name: Set Lowercase Username
        id: lowercase_username
        run: echo "::set-output name=username::${GITHUB_ACTOR,,}"

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -f LN-history.Startup/Dockerfile -t ghcr.io/${{ steps.lowercase_username.outputs.username }}/ln-history:latest .

       # Authenticate GHCR
      - name: Authenticate to GHCR
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      # Push Docker Image
      - name: Push Docker Image
        run: docker push ghcr.io/${{ steps.lowercase_username.outputs.username }}/ln-history:latest

      # Deploy to VPS
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/docker/ln-history
            docker-compose pull
            docker-compose down
            docker-compose up -d
